Screen-Devs/book-nook

.gitignore
client/dist/index.html
package-lock.json
package.json
server/index.js

Hey guys,
This PR is just to get the basic skeleton structure of the project set up. It'll have the following file structure.
```
.
|---client
|     |---dist
|     |      |---index.html
|     |      |---styles.css
|     |---src
|            |---components
|            |     |---(all react components)
|            |---index.jsx
|---database
|     |---models
|           |--- (all models used to make queries for our database of choice)
|           |---index.js (not created yet, but could be for our connection to the database)
|---server
|---controllers
|     |---(all server side controllers to invoke models)
|---routes.js(not created yet, but if our endpoints do get hefty, we can probably import express middleware)
|---index.js (for rendering our client static)

Project init

---

database/models/api.js
database/models/book.js
database/models/user.js
server/controller/authenticate.js
server/controller/book.js
server/controller/index.js
server/controller/user.js
server/routes.js

This is a larger PR - apologies for that! - meant to set up and flesh out server architecture.
Request routing, controller functions, and database/api queries are separated out according to a typical MVC format.
(In /server/routes.js):
--[x] Added 'user' routes
--[x] Added 'book' routes
--[x] Added 'external api' routes
(In /server/controller folder)
--[x] Added book.js (linked to 'database/models/book.js)
----[x] added 'getBook' controller (get individual book data from google api and combine with DB metadata)
----[x] added 'addReview' controller
----[x] added 'addComment' controller
--[x] Added user.js (linked to 'database/models/user.js)
----[x] added 'getUserInfo' controller (for populating user homepages)
----[x] added 'addBook' controller 
----[x] added 'addFriend' controller …

set up route architecture

---

database/models/bookdata.js
server/controller/book.js
server/routes.js

Got nested db queries working 
This allows controller functions to interact properly with db queries.
[x] wrote them queries
yas
n/a
n/a

wrote workable queries for book model

---

database/index.js
database/models/bookdata.js

fix merge conflicts in database schemas

---

server/controller/outbound.js

Fixed API key so destructing is no longer needed.

fixed api key so destructering is no longer needed

---

client/src/components/App.jsx
client/src/components/Home.jsx
client/src/components/RightComponent/NYTModal/NYTModal.jsx
client/src/requests/index.js

Refactored a couple of request out of home

Request refactors

---

client/src/components/CenterComponent/BookReviews/BookDetails/BookDetails.jsx
client/src/components/CenterComponent/BookReviews/BookDetails/sample.js
client/src/components/CenterComponent/BookReviews/BookReviews.jsx

book detail using sample data

---

client/src/components/LeftComponent/LeftComponent.jsx

Fix the missing left component

fix left component render

---

client/src/components/CenterComponent/BookReviews/BookDetails/BookDetails.jsx
client/src/components/CenterComponent/Search.jsx
client/src/components/CenterComponent/SearchResultCard.jsx

fixed bug on book details button

---

client/src/components/CenterComponent/ProfileComments.jsx
database/index.js
database/models/user.js
server/controller/user.js
server/routes.js

Builds out route and model for GET /users/leaderboards?u=XXX
Returns leaderboard meta data for a user's friends list.

Leaderboard backend functionality 

---

client/src/components/Home.jsx
client/src/components/LeftComponent/LeftComponent.jsx
client/src/components/RightComponent/RightComponent.jsx

This PR is to debug the conditional rendering logic of left, center, and right components

debug component rendering on certain views

---

client/src/components/CenterComponent/BookReviews/BookDetails/CommentAccordian/CommentAccordian.jsx
client/src/components/CenterComponent/BookReviews/BookReviews.jsx
client/src/components/CenterComponent/BookReviews/Comments.jsx
client/src/components/CenterComponent/BookReviews/TopReviews.jsx

minor css fixes on book review page

minor css fixes on book review page

---

client/src/components/RightComponent/Leaderboard/Leaderboard.jsx
client/src/components/RightComponent/Leaderboard/MostClubbed.jsx
client/src/components/RightComponent/Leaderboard/MostCompleted.jsx
client/src/components/RightComponent/NYTModal/NYTModal.jsx
client/src/components/RightComponent/SiteData.jsx

added leaderboard with sample data
https://user-images.githubusercontent.com/86852189/152293778-71dcd725-e727-4c3a-b1a4-4f8ab1625820.mov

added leaderboard with sample data

---

client/src/components/CenterComponent/SearchResultCard.jsx

fixed placeholder image sizing on search page

---

client/src/components/RightComponent/FriendsList/FriendsList.jsx
client/src/components/RightComponent/SiteData.jsx

Fixed sizing of friends list to fit suggested books component

fixed sizing of friends list to fit suggested books

---

client/src/components/CenterComponent/BookReviews/AddReviewModal.jsx
client/src/components/CenterComponent/BookReviews/BookDetails/CommentAccordian/CommentAccordian.jsx
client/src/components/CenterComponent/BookReviews/BookReviews.jsx
client/src/components/CenterComponent/BookReviews/Comments.jsx
client/src/components/CenterComponent/BookReviews/CommentsWithinReview.jsx
client/src/components/CenterComponent/BookReviews/DropdownReviews.jsx
client/src/components/CenterComponent/BookReviews/TopReviews.jsx
client/src/components/CenterComponent/CenterComponent.jsx
client/src/components/CenterComponent/ProfileComments.jsx
client/src/components/Home.jsx
client/src/components/RightComponent/NYTModal/NYTModal.jsx
client/src/components/RightComponent/RightComponent.jsx
client/src/requests/index.js
client/src/styles.css
database/models/bookdata.js
package-lock.json

Add friend button (it's an anchor but you can change it) will now only render if a user is not your friend. After clicking it, it will disappear.

Add friend

---

client/src/components/CommentModule.jsx
package-lock.json
package.json

Imports timeago library
Formats date on profile comments.

Profile comments date format

---

client/src/components/RightComponent/SiteData.jsx
client/src/components/RightComponent/SuggestedBooks/SuggestedCarousel.jsx
client/src/components/RightComponent/SuggestedBooks/SuggstedBooks.jsx
client/src/requests/index.js

Suggested book list now populates data used the back end algorithm. 
FYI, for error handling, I added a conditional message that renders if the suggestedBook data comes back empty. It looks like so:

Integrate suggested book list

---

client/src/components/CenterComponent/BookReviews/AddCommentModal.jsx
client/src/components/CenterComponent/BookReviews/BookReviews.jsx
client/src/components/CenterComponent/BookReviews/CommentsWithinReview.jsx
client/src/components/CenterComponent/BookReviews/DropdownComments.jsx
client/src/components/CenterComponent/BookReviews/Reviews.jsx
package-lock.json

- implemented review and comment post request functionality on front end

implemented review and comment post request functionality on front end

---

client/src/components/CenterComponent/BookReviews/BookDetails/CommentAccordian/CommentAccordian.jsx
client/src/components/CenterComponent/BookReviews/CommentsWithinReview.jsx
client/src/components/CenterComponent/BookReviews/DropdownComments.jsx
client/src/components/CenterComponent/BookReviews/Reviews.jsx

also fixed styling on comments
https://user-images.githubusercontent.com/86852189/152444986-9cc802f3-9307-4720-bc37-f8f84f1b726d.mov

added helpful and report on click func on each comment

---

client/src/components/CenterComponent/BookReviews/CommentsWithinReview.jsx
client/src/components/CenterComponent/BookReviews/Reviews.jsx
package-lock.json
package.json

be sure to npm install, added new dependency 'dayjs'

added dayjs to format dates, fixed some formatting on reviews/comments

---

client/src/components/CenterComponent/SearchResultCard.jsx
client/src/components/RightComponent/Leaderboard/Leaderboard.jsx
client/src/components/RightComponent/SuggestedBooks/SuggestedCarousel.jsx
database/models/user.js

Swaps dummy data for live data in the Suggested Carousel modal.
Also includes a leaderboard fix that was causing a 400 error.

Suggested modal integration

---

client/src/components/CenterComponent/BookReviews/BookDetails/CommentAccordian/CommentAccordian.jsx
client/src/components/CenterComponent/BookReviews/CommentsWithinReview.jsx
client/src/components/CenterComponent/BookReviews/DropdownComments.jsx
client/src/components/CenterComponent/BookReviews/Reviews.jsx

*Implemented 'put' request functionality for marking reviews/comments helpful or reporting reviews/comments
note: Still need front-end logic to deny rendering of reported reviews/comments;
note2: also need front-end logic to re-render with new data (incremented helpful count / reported)
note3: will also need a way to block user from incrementing helpful multiple times

Implement 'puts' 

---

client/src/components/CenterComponent/ProfileComments.jsx
client/src/styles.css
database/models/user.js
package-lock.json

Resizes username header component
Adds conditional rendering based on if a user is on their own page vs another user's. 
Usernames who are on your friends list will appear in beige.

Username header & add friend styling

---

client/src/components/RightComponent/SiteData.jsx

Fix leaderboard not rendering suggestions properly- the prop passed down was overwritten in a previous PR.

Leaderboard fix

---

client/src/components/CenterComponent/CenterComponent.jsx
client/src/components/CommentModule.jsx
client/src/components/Home.jsx

You can now click a friends name in your comments to see them.

Friend comment link fix

---

client/src/components/CenterComponent/Search.jsx
client/src/components/CommentModule.jsx
client/src/components/RightComponent/FriendsList/FriendsModal.jsx
client/src/styles.css

fixed the styling for the css

---

client/src/components/Footer.jsx
client/src/styles.css

added footer with our linkedin profiles linked

---

client/src/components/CenterComponent/BookReviews/TopReviews.jsx

changed placeholder title to reviews

---

package-lock.json
package.json
server/index.js

*included cors middleware for deployed server to allow access

updated to allow cross origin requests

---

client/src/requests/index.js

un-specified localhost from all client-side requests

un-specified localhost from all client-side requests

---

README.md

drafted readme

---

README.md
client/src/components/CenterComponent/Search.jsx

Added some notes to the readme

Added external API

---

README.md

added API routes for book metadata to readme

added API routes for book metadata to readme
